from __future__ import annotations

from typing import Dict

WIKIDATA_PROPERTIES: Dict[str, str] = {
    # === BASIC IDENTITY ===
    "P31": "instance of (what type of thing it is)",
    "P279": "subclass of (parent class)",
    "P373": "Commons category",
    "P18": "image",
    "P910": "topic's main category",
    # === PERSON - BIOGRAPHICAL ===
    "P569": "date of birth",
    "P570": "date of death",
    "P19": "place of birth",
    "P20": "place of death",
    "P27": "country of citizenship",
    "P21": "sex or gender",
    "P106": "occupation",
    "P22": "father",
    "P25": "mother",
    "P26": "spouse",
    "P40": "child",
    "P3373": "sibling",
    "P1038": "relative",
    "P103": "native language",
    "P1412": "languages spoken/written",
    "P551": "residence",
    "P119": "place of burial",
    "P509": "cause of death",
    "P1196": "manner of death",
    "P140": "religion or worldview",
    "P102": "member of political party",
    "P241": "military branch",
    "P410": "military rank",
    "P607": "conflict (participated in)",
    # === PERSON - PROFESSIONAL/EDUCATION ===
    "P69": "educated at (school/university)",
    "P512": "academic degree",
    "P812": "academic major",
    "P108": "employer",
    "P101": "field of work",
    "P800": "notable work",
    "P166": "award received",
    "P1411": "nominated for",
    "P184": "doctoral advisor",
    "P185": "doctoral student",
    "P1066": "student of (mentor)",
    "P802": "student (taught by this person)",
    "P463": "member of (organization/society/international org)",
    "P39": "position held",
    "P1830": "owner of",
    # === SCIENTIST SPECIFIC ===
    "P737": "influenced by",
    "P1416": "affiliation (research institution)",
    "P859": "sponsor (research funding)",
    "P5008": "on focus list of Wikimedia project",
    "P1441": "present in work (mentioned in)",
    "P2561": "name (official/formal name)",
    # === ARTIST/MUSICIAN SPECIFIC ===
    "P264": "record label",
    "P412": "voice type",
    "P1303": "instrument played",
    "P527": "has part (band members, album tracks, components)",
    "P361": "part of (band, collective, larger entity)",
    "P135": "movement (artistic/cultural/literary)",
    "P180": "depicts (subject of artwork)",
    "P186": "made from material",
    "P2048": "height (artwork dimensions)",
    "P2049": "width (artwork dimensions)",
    "P195": "collection (museum/gallery holding)",
    "P1071": "location of creation",
    "P170": "creator (for artworks)",
    "P144": "based on (source material/software)",
    "P941": "inspired by",
    # === WRITER/AUTHOR SPECIFIC ===
    "P6886": "writing language",
    "P7937": "form of creative work",
    "P1433": "published in (journal/venue)",
    "P921": "main subject",
    "P2093": "author name string",
    # === POLITICIAN/LEADER SPECIFIC ===
    "P1308": "officeholder",
    "P1313": "office held by head of government",
    "P6": "head of government",
    "P35": "head of state",
    "P194": "legislative body",
    "P768": "electoral district",
    "P4100": "parliamentary group",
    "P1532": "country for sport",
    "P945": "allegiance",
    # === ATHLETE/SPORTS PERSON ===
    "P54": "member of sports team",
    "P413": "position played",
    "P286": "head coach",
    "P647": "drafted by",
    "P1618": "sport number",
    "P1352": "ranking",
    "P1346": "winner",
    "P1350": "number of matches played",
    "P1351": "number of points/goals/set scored",
    # === ORGANIZATION ===
    "P571": "inception date (when founded)",
    "P576": "dissolved date",
    "P112": "founded by",
    "P159": "headquarters location",
    "P17": "country",
    "P452": "industry",
    "P127": "owned by",
    "P749": "parent organization",
    "P355": "subsidiary",
    "P169": "chief executive officer",
    "P488": "chairperson",
    "P3320": "board member",
    "P856": "official website",
    "P2196": "student count",
    "P1128": "employees/staff count",
    "P154": "logo image",
    "P968": "email address",
    "P1329": "phone number",
    "P2002": "Twitter/X username",
    "P2013": "Facebook ID",
    "P2003": "Instagram username",
    "P2397": "YouTube channel ID",
    # === EDUCATIONAL INSTITUTION ===
    "P131": "located in administrative unit",
    "P6375": "street address",
    "P1813": "short name",
    "P1449": "nickname",
    "P5124": "Wikimedia outline",
    "P1365": "replaces",
    "P1366": "replaced by",
    # === PLACE / GEOGRAPHY ===
    "P36": "capital",
    "P1376": "capital of",
    "P30": "continent",
    "P1082": "population",
    "P2046": "area",
    "P37": "official language",
    "P38": "currency",
    "P47": "shares border with",
    "P2044": "elevation",
    "P421": "timezone",
    "P625": "coordinates",
    "P610": "highest point",
    "P1589": "lowest point",
    "P206": "located on body of water",
    "P205": "basin country",
    "P403": "mouth of watercourse",
    "P885": "origin of watercourse",
    "P2043": "length",
    "P4552": "mountain range",
    "P2936": "language used",
    "P1151": "topic's main Wikimedia portal",
    # === COUNTRY/STATE SPECIFIC ===
    "P122": "basic form of government",
    "P85": "anthem",
    "P163": "flag",
    "P94": "coat of arms",
    "P1906": "office held by head of state",
    "P530": "diplomatic relation",
    "P190": "twinned administrative body",
    "P2852": "emergency phone number",
    "P2853": "police phone number",
    "P2855": "fire phone number",
    # === CREATIVE WORKS (GENERAL) ===
    "P50": "author",
    "P57": "director",
    "P161": "cast member",
    "P162": "producer",
    "P58": "screenwriter",
    "P1040": "film editor",
    "P344": "director of photography",
    "P86": "composer",
    "P175": "performer",
    "P577": "publication date",
    "P123": "publisher",
    "P136": "genre",
    "P495": "country of origin",
    "P364": "original language of film/TV",
    "P2047": "duration",
    "P840": "narrative location (setting)",
    "P674": "characters",
    "P1431": "executive producer",
    "P272": "production company",
    "P750": "distributed by",
    "P2758": "CNC film rating (France)",
    "P1657": "MPA film rating",
    "P444": "review score",
    "P2142": "box office",
    "P2130": "cost/budget",
    # === BOOK/LITERATURE ===
    "P407": "language of work",
    "P747": "has edition or translation",
    "P629": "edition or translation of",
    "P1104": "number of pages",
    "P2969": "goodreads ID",
    "P212": "ISBN-13",
    "P957": "ISBN-10",
    "P179": "part of series",
    "P155": "preceded by (in series)",
    "P156": "followed by (in series)",
    # === MUSIC ===
    "P658": "tracklist",
    "P435": "MusicBrainz work ID",
    "P1243": "ISRC",
    "P1954": "discogs master ID",
    "P436": "MusicBrainz release group ID",
    "P826": "tonality",
    "P1922": "first line",
    "P676": "lyrics by",
    "P87": "librettist",
    # === SCIENCE / ACADEMIC ===
    "P61": "discoverer or inventor",
    "P138": "named after",
    "P575": "time of discovery/invention",
    "P1343": "described by source",
    "P2670": "has part(s) of the class",
    "P366": "has use",
    "P1552": "has characteristic",
    "P2275": "World Health Organization essential medicines",
    # === CHEMICAL/MEDICAL ===
    "P231": "CAS Registry Number",
    "P662": "PubChem CID",
    "P683": "ChEBI ID",
    "P2067": "mass",
    "P274": "chemical formula",
    "P117": "chemical structure",
    "P2175": "medical condition treated",
    "P3489": "pregnancy category",
    "P769": "significant drug interaction",
    # === BIOLOGY / SPECIES ===
    "P225": "taxon name (scientific name)",
    "P105": "taxon rank",
    "P171": "parent taxon",
    "P141": "IUCN conservation status",
    "P1843": "common name (taxon)",
    "P2974": "habitat",
    "P183": "endemic to (native region)",
    "P4003": "diet",
    "P181": "taxon range map image",
    "P815": "ITIS TSN",
    "P685": "NCBI taxonomy ID",
    "P846": "GBIF taxon ID",
    "P627": "IUCN taxon ID",
    # === SPORTS (GENERAL) ===
    "P797": "governing body",
    "P2283": "equipment used",
    "P115": "venue/home stadium",
    "P425": "team size",
    "P1344": "participant in (event/competition)",
    "P2266": "contact type (sport)",
    "P641": "sport",
    "P1923": "participating team",
    "P118": "league",
    "P2094": "competition class",
    # === EVENTS ===
    "P585": "point in time (when event occurred)",
    "P580": "start time",
    "P582": "end time",
    "P276": "location",
    "P710": "participant",
    "P664": "organizer",
    "P1120": "number of deaths",
    "P1339": "number of injured",
    "P1590": "number of casualties",
    # === TECHNOLOGY/SOFTWARE ===
    "P178": "developer",
    "P277": "programming language",
    "P306": "operating system",
    "P348": "software version",
    "P400": "platform",
    "P1547": "depends on software",
    "P2700": "protocol",
    "P275": "license",
    "P1324": "source code repository URL",
    # === IDENTIFIERS ===
    "P214": "VIAF ID",
    "P227": "GND ID",
    "P244": "Library of Congress authority ID",
    "P213": "ISNI",
    "P496": "ORCID iD",
    "P2456": "DBLP author ID",
    "P1960": "Google Scholar author ID",
    "P549": "Mathematics Genealogy Project ID",
    "P646": "Freebase ID",
    "P345": "IMDb ID",
    "P1566": "GeoNames ID",
}
